# Generated by Django 5.1.4 on 2025-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('News', 'News'), ('Event', 'Event')], max_length=32, verbose_name='News Type')),
                ('short_description', models.TextField(max_length=200)),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('news_image', models.ImageField(help_text='Upload News Image', upload_to='news_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
