"""
Django settings for artisan project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!+aw+py)mix+-3pla=0=nl05iv=_syd2#20-&wco$$8%-(7exq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #3rd party libraries
    'unfold',
    'rest_framework',
    #Add apps here
    'products',
    'message',
    'career',
    'hero',
    'catalog',
    'news',
    'executive',
    'directorboard',
    
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
]

ROOT_URLCONF = 'artisan.urls'
AUTO_LOGOUT = {
    'IDLE_TIME': timedelta(hours=12),
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'artisan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'artisan',
        'USER': 'root',
        'PASSWORD': 'Minato@420',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

UNFOLD = {
    "SITE_TITLE": "Artisan Ceramics Ltd.",
    "SITE_HEADER": "Artisan Ceramics Ltd.",
    "SITE_URL": "/",
    "SITE_ICON":"",
    "SITE_LOGO": {
            "light": "/static/images/logo-light.png",  # light mode
            "dark": "/static/images/logo.png", 
    },
    "SITE_SYMBOL": "speed",
    # "SITE_FAVICON": [
    #     {
    #         "rel": "icon",
    #         "sizes": "6x6",
    #         "type": "image/svg+xml",
    #         "href": "/static/images/logo-light.png",
    #     },
    # ],
    "SIDEBAR": {
            "show_search": True,  # Search in applications and models names
            "show_all_applications": True,  # Dropdown with all applications and models
            "navigation": [
                {
                    "title": _("User Management"),
                    
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("Users"),
                            "icon": "Person",
                              # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:auth_user_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        {
                            "title": _("Authorization"),
                            "icon": "Security",
                              # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:auth_group_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                        
                    ],
                },
                {
                    "title": _("Products"),
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("Categories"),
                            "icon": "category",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:products_category_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        {
                            "title": _("Shapes"),
                            "icon": "shapes",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:products_shape_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        {
                            "title": _("Products"),
                            "icon": "coffee",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:products_product_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                        
                    ],
                },
                {
                    "title": _("Catalogs"),
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("View All Catalog"),
                            "icon": "book_2",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:catalog_catalog_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                        
                    ],
                },
                {
                    "title": _("News"),
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("View All News"),
                            "icon": "News",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:news_news_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                        
                    ],
                },
                {
                    "title": _("Career"),
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("Job Post"),
                            "icon": "work",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:career_job_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                    ],
                },
                {
                    "title": _("Message"),
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("Inbox"),
                            "icon": "inbox",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:message_inbox_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                    ],
                },
                {
                    "title": _("Home Page"),
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("Home Page Video"),
                            "icon": "play_arrow",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:hero_herosection_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        {
                            "title": _("Product Showcase"),
                            "icon": "perm_media",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:hero_showcase_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        {
                            "title": _("Brand Video"),
                            "icon": "smart_display",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:hero_brandvideo_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                    ],
                },
                {
                    "title": _("Directors"),
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("List of Directors"),
                            "icon": "person",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:directorboard_directorboard_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                        
                    ],
                },
                {
                    "title": _("Executive Members"),
                    "separator": True,  # Top border
                    "collapsible": True,  # Collapsible group of links
                    "items": [
                        {
                            "title": _("List of Executives"),
                            "icon": "person",  # Supported icon set: https://fonts.google.com/icons
                            "link": reverse_lazy("admin:executive_executive_changelist"),
                            
                            "permission": lambda request: request.user.is_superuser,
                        },
                        
                        
                    ],
                },
            ]
    }
}