# Generated by Django 5.1.4 on 2025-01-13 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='catalog/')),
                ('pdf_file', models.FileField(default='catalogs/default.pdf', upload_to='catalog/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
    ]
