# Generated by Django 5.1.4 on 2025-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Job Title')),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IN', 'Internship')], max_length=2, verbose_name='Job Type')),
                ('location', models.CharField(choices=[('Head Office', 'Head Office'), ('Factory', 'Factory')], max_length=50, verbose_name='Location')),
                ('salary', models.CharField(max_length=32, verbose_name='Salary')),
                ('vacancy', models.PositiveIntegerField(verbose_name='Vacancy')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('description', models.TextField(verbose_name='Job Description')),
            ],
        ),
    ]
